name: 简release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.32.1)'
        required: true
        default: 'v1.32.1'
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build static export
        run: bun run build

      - name: Compress dist folder
        run: zip -r dist.zip dist

      - name: Set release tag
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "tag=${{ inputs.release_tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set-tag.outputs.tag }}
          files: dist.zip

      - name: Generate changelog
        run: bun x changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
